model:
  hidden_layers:
  - 128
  - 128
  - 64
  - 32
  num_states: 15
paths:
  checkpoint: results/best_pinns_model.pt
  metrics: results/metrics_pinns.json
physics:
  E_table11:
    '-1.0':
    - 1.15240356610875
    - 3.133072078423746
    - 5.153044904738095
    - 7.180799992236852
    - 9.208256528810605
    - 11.23332995500909
    - 13.25572511908875
    - 15.27569025487764
    - 17.29366091681522
    - 19.31070729982288
    - 21.33240859799286
    - 23.38247329756196
    - 25.51798403644317
    - 27.80948687706467
    - 30.30024608646104
    '-10.0':
    - -2.212027077408593
    - -0.1400966315254728
    - 2.036552641619089
    - 4.269827427931567
    - 6.512980993499115
    - 8.742291625095396
    - 10.94895053586326
    - 13.13143394139445
    - 15.2913344361363
    - 17.43146041910349
    - 19.55617191908625
    - 21.67812723985919
    - 23.8368710588819
    - 26.10611654504134
    - 28.55546223359175
    '-15.0':
    - -4.209444206755376
    - -1.971875448569706
    - 0.3101718010128308
    - 2.643441590867051
    - 4.993028316124443
    - 7.329329090237381
    - 9.637355855457159
    - 11.91226508709537
    - 14.15458256485327
    - 16.36726848930564
    - 18.55472250436049
    - 20.72634242696661
    - 22.9118772998944
    - 25.17872893713468
    - 27.60714184339666
    '-5.0':
    - -0.2957769212457393
    - 1.674982118067129
    - 3.764484893364237
    - 5.890216961632051
    - 8.01773930971414
    - 10.1351169760011
    - 12.23930885577595
    - 14.33061774153351
    - 16.41048785040598
    - 18.4809248714588
    - 20.54659497214019
    - 22.62540693812649
    - 24.7672277103157
    - 27.04651663261225
    - 29.51868951359004
  Lambda: -0.001
  V0: -1.0
  domain_L: 3.0
training:
  colocation_points: 2000
  epochs: 20000
  learning_rate: 0.0003
  seed: 42
  "weight_ordena\xE7\xE3o": 50.0
  weight_ortogonalidade: 500.0
